name: Deploy Documentation

on:
  push:
    branches:
      - main # Déclenche la publication de la doc à chaque push sur la branche main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: poetry install

      # Génération de la doc via Sphinx
      - name: Build HTML Documentation
        run: |
          cd docs
          poetry run make html

      # 1/5 - Publication sur GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4